title: Anshaj Khare
logo: "/images/logo1.png?raw=true"
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  Experienced machine learning engineer with experience in building full-scale backend and ML projects.
    <br><br>
  <a href="https://thecomputeblog.substack.com">âœğŸ» My tech blog</a> <br>
  <a href="https://www.linkedin.com/in/anshaj-khare/">ğŸ‘” Connect with me on LinkedIn</a><br>
  <a href="https://topmate.io/anshaj">ğŸ“ 1:1 call with me</a><br>
  <a href="https://anshaj.com">ğŸ“¸ My photography blog</a> <br>
theme: jekyll-theme-minimal
